// Generated by `pnpm --filter db codegen` from a running Supabase instance.
// Phase 1 placeholder — replaced once Supabase project exists.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      team_role:
        | "owner"
        | "planner"
        | "stylist"
        | "admin"
        | "external_assistant";
    };
    CompositeTypes: Record<string, never>;
  };
};
